### ISSUE TITLE
File `chunker.py` missing

### ISSUE THREAD

**Issue by leleogere** [TimFelixBeyer/MIDI2ScoreTransformer#1]
Hello,

Thank you for sharing your code for your paper! This work is very interesting!

In the readme, you mention a file `chunker.py` to create the beat-aligned chunks. However, I can't find it anywhere. Maybe you forgot to commit it?

Thank you!

**Comment by TimFelixBeyer** [comment]
Thanks for letting me know, I forgot indeed! It should be uploaded now.
